version: '3.8'

services:
  # Redis: Message broker for Celery
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=Data
      - POSTGRES_PASSWORD=DataICMC
      - POSTGRES_DB=DataDaColeta
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

  # Backend API Service (FastAPI)
  backend:
    build: .
    command: uvicorn src.backend.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  # Computer Vision Worker (Celery)
  worker:
    build: .
    command: celery -A src.worker.tasks worker --loglevel=info
    volumes:
      - ./src:/app/src
    depends_on:
      - redis

  # Telegram Bot
  bot:
    build: .
    command: python src/bot/bot.py
    volumes:
      - ./src:/app/src
    depends_on:
      - backend

volumes:
  postgres_data:  