from fastapi import FastAPI, HTTPException, Depends, UploadFile, File, Form
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, Session
from pydantic import BaseModel
from datetime import datetime
import os
import uuid
import shutil
from pathlib import Path

from ..database import models
from ..worker.tasks import process_submission

# --- Database Configuration ---
DATABASE_URL = os.getenv("DATABASE_URL")
if not DATABASE_URL:
    # This will raise an error if DATABASE_URL is not set, which is good for early detection
    raise ValueError("DATABASE_URL environment variable not set.")

# --- File Storage Configuration ---
UPLOADS_DIR = Path(os.getenv("UPLOADS_DIR", "uploads"))
UPLOADS_DIR.mkdir(exist_ok=True) # Create the directory on startup if it doesn't exist

engine = create_engine(DATABASE_URL)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

# Create the table in the database (FastAPI can do this on startup)
# This command creates all tables that inherit from models.Base
models.Base.metadata.create_all(bind=engine)

# --- Pydantic Models (for request/response validation) ---
# Schemas for Team
class TeamBase(BaseModel):
    name: str

# TeamCreate needs event_id because it's part of the composite primary key
class TeamCreate(TeamBase):
    event_id: int

class TeamResponse(TeamBase):
    id: int
    score: int
    event_id: int
    thread_id: str | None = None
    class Config:
        from_attributes = True # Allows Pydantic to read data from ORM models

class TeamUpdate(BaseModel):
    thread_id: str

# Schemas for Event
class EventBase(BaseModel):
    date: datetime

class EventCreate(EventBase):
    pass

class EventResponse(EventBase):
    id: int
    class Config:
        from_attributes = True

# Schemas for Participant
class ParticipantBase(BaseModel):
    id: str # Telegram ID or username
    name: str

class ParticipantCreate(ParticipantBase):
    team_id: int

class ParticipantResponse(ParticipantBase):
    team_id: int
    class Config:
        from_attributes = True

# Schemas for Submission
class SubmissionBase(BaseModel):
    timestamp: datetime | None = None # Allow client to provide, or default to now
    latitude: str | None = None
    longitude: str | None = None
    # photo_path is removed because it's generated by the server, not provided by the client.
    # The other fields (participant_id, team_id) will be sent as form data alongside the file.


class SubmissionResponse(SubmissionBase):
    id: int
    participant_id: str
    team_id: int
    litter_type: str | None = None
    points_awarded: int
    status: str
    photo_path: str # Add photo_path to the response
    class Config:
        from_attributes = True


# --- FastAPI Application ---
app = FastAPI(
    title="Data da Coleta API",
    description="Backend service for the Data da Coleta competition.",
    version="1.0.0"
)

# --- Dependency for getting a DB session ---
def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

# --- API Endpoints for Teams ---
@app.post("/teams/", response_model=TeamResponse, status_code=201)
def create_team(team: TeamCreate, db: Session = Depends(get_db)):
    """
    Creates a new team in the database.
    - **RF01**: Allows for the creation of teams.
    """
    # Check if a team with the same name already exists for the given event (composite primary key check)
    db_team = db.query(models.Team).filter(
        models.Team.name == team.name,
        models.Team.event_id == team.event_id
    ).first()

    if db_team:
        raise HTTPException(status_code=400, detail=f"Team '{team.name}' already exists in this event.")
    
    new_team = models.Team(
        name=team.name,
        event_id=team.event_id
    )
    db.add(new_team)
    db.commit()
    db.refresh(new_team)
    return new_team

@app.get("/teams/", response_model=list[TeamResponse])
def get_teams(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    """
    Retrieves a list of all teams.
    """
    teams = db.query(models.Team).offset(skip).limit(limit).all()
    return teams

@app.get("/teams/{team_id}", response_model=TeamResponse)
def get_team(team_id: int, db: Session = Depends(get_db)):
    """
    Retrieves a single team by its ID.
    """
    team = db.query(models.Team).filter(models.Team.id == team_id).first()
    if not team:
        raise HTTPException(status_code=404, detail="Team not found")
    return team

@app.patch("/teams/{team_id}", response_model=TeamResponse)
def update_team_thread_id(team_id: int, team_update: TeamUpdate, db: Session = Depends(get_db)):
    """
    Updates the thread_id of a team.
    """
    db_team = db.query(models.Team).filter(models.Team.id == team_id).first()
    if not db_team:
        raise HTTPException(status_code=404, detail="Team not found")
    db_team.thread_id = team_update.thread_id
    db.commit()
    db.refresh(db_team)
    return db_team

@app.get("/ranking/", response_model=list[TeamResponse])
def get_ranking(db: Session = Depends(get_db)):
    """
    Retrieves a list of all teams, ordered by score in descending order.
    - **RF08**: Exibir ranking atual através de comando.
    """
    teams = db.query(models.Team).order_by(models.Team.score.desc()).all()
    return teams

# --- API Endpoints for Events ---
@app.post("/events/", response_model=EventResponse, status_code=201)
def create_event(event: EventCreate, db: Session = Depends(get_db)):
    """
    Creates a new event.
    """
    # In a real app, you might want to check for overlapping event dates or names
    new_event = models.Event(date=event.date)
    db.add(new_event)
    db.commit()
    db.refresh(new_event)
    return new_event

@app.get("/events/", response_model=list[EventResponse])
def get_events(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    """
    Retrieves a list of all events.
    """
    events = db.query(models.Event).order_by(models.Event.date.desc()).offset(skip).limit(limit).all()
    return events

@app.get("/events/{event_id}", response_model=EventResponse)
def get_event(event_id: int, db: Session = Depends(get_db)):
    """
    Retrieves a single event by its ID.
    """
    event = db.query(models.Event).filter(models.Event.id == event_id).first()
    if not event:
        raise HTTPException(status_code=404, detail="Event not found")
    return event

# --- API Endpoints for Participants ---
@app.post("/participants/", response_model=ParticipantResponse, status_code=201)
def create_participant(participant: ParticipantCreate, db: Session = Depends(get_db)):
    """
    Registers a new participant to a team.
    - **RF01**: Allows people to choose their groups (by providing team_id).
    """
    # Check if participant with this ID already exists
    db_participant = db.query(models.Participant).filter(models.Participant.id == participant.id).first()
    if db_participant:
        raise HTTPException(status_code=400, detail=f"Participant with ID '{participant.id}' already exists.")

    # Check if the team exists
    db_team = db.query(models.Team).filter(models.Team.id == participant.team_id).first()
    if not db_team:
        raise HTTPException(status_code=404, detail=f"Team with ID '{participant.team_id}' not found.")

    new_participant = models.Participant(
        id=participant.id,
        name=participant.name,
        team_id=participant.team_id
    )
    db.add(new_participant)
    db.commit()
    db.refresh(new_participant)
    return new_participant

@app.get("/participants/", response_model=list[ParticipantResponse])
def get_participants(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    """
    Retrieves a list of all participants.
    """
    participants = db.query(models.Participant).offset(skip).limit(limit).all()
    return participants

@app.get("/participants/{participant_id}", response_model=ParticipantResponse)
def get_participant(participant_id: str, db: Session = Depends(get_db)):
    """
    Retrieves a single participant by their ID.
    """
    participant = db.query(models.Participant).filter(models.Participant.id == participant_id).first()
    if not participant:
        raise HTTPException(status_code=404, detail="Participant not found")
    return participant

# --- API Endpoints for Submissions ---
@app.post("/submissions/", response_model=SubmissionResponse, status_code=201)
def create_submission(
    db: Session = Depends(get_db),
    photo: UploadFile = File(...),
    participant_id: str = Form(...),
    latitude: str | None = Form(None),
    longitude: str | None = Form(None)
):
    """
    Creates a new submission (e.g., from a bot).
    Accepts multipart/form-data with a photo file and metadata.
    - **RF04**: Upload simultaneous images with metadata (GPS, timestamp).
    - **RF07**: Register each submission (image, class, points, user, team).
    """
    # --- Validation ---
    # 1. Find the participant in the database
    participant = db.query(models.Participant).filter(models.Participant.id == participant_id).first()
    if not participant:
        raise HTTPException(status_code=404, detail=f"Participant with ID '{participant_id}' not found.")
    
    # 2. Get the team_id from the participant
    team_id = participant.team_id

    # --- File Handling ---
    # Generate a unique filename to prevent overwrites
    file_extension = Path(photo.filename).suffix
    unique_filename = f"{uuid.uuid4().hex}{file_extension}"
    file_path = UPLOADS_DIR / unique_filename

    # Save the uploaded file to the local folder
    try:
        with file_path.open("wb") as buffer:
            shutil.copyfileobj(photo.file, buffer)
    except IOError:
        # This will catch file-saving errors, e.g., disk full, permissions
        raise HTTPException(status_code=500, detail="Failed to save the uploaded photo.")
    finally:
        photo.file.close()

    # --- Database Operation ---
    new_submission = models.Submission(
        participant_id=participant_id,
        team_id=team_id, # Use the looked-up team_id
        photo_path=str(file_path), # Store the path as a string
        timestamp=datetime.utcnow(),
        latitude=latitude,
        longitude=longitude,
        status='pending_processing' # Initial status before AI processing
    )
    db.add(new_submission)
    db.commit()
    db.refresh(new_submission)

    # --- Queue Task for Processing ---
    process_submission.delay(new_submission.id)

    return new_submission

@app.get("/")
def read_root():
    return {"message": "Welcome to the Data da Coleta API!"}
